---
- name: manage Ceph
  hosts: all
  # strategy: free
  become: true

  tasks:
    - name: Set up ssh config on each host
      include_tasks: ssh.yml

    - name: install dependencies
      include_tasks: pkgs.yml

    - name: Use the k8s apt key
      get_url:
        url: "https://pkgs.k8s.io/core:/stable:/v{{ k8sVersion }}/deb/Release.key"
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: "0644"

    - name: Install k8s apt sources
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ k8sVersion }}/deb/ /"
        state: present

    - name: Install main packages
      apt:
        pkg: "{{ item }}"
      loop:
        - kubelet
        - kubeadm
        - kubectl
        - containerd

    - name: Hold kubeadm
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable kubelet
      systemd_service:
        name: kubelet
        state: stopped

